// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.grpc.java.testing_service;

public final class TestingServiceProto {
  private TestingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_service_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_service_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_service_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_service_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\014user_service\"2\n\014LoginReque" +
      "st\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"<" +
      "\n\013APIResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\0052H\n\004User\022@\n\005login\022\032." +
      "user_service.LoginRequest\032\031.user_service" +
      ".APIResponse\"\000B;\n\034io.grpc.java.testing_s" +
      "erviceB\023TestingServiceProtoP\001\242\002\003HLWb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_service_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_service_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_service_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_user_service_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_service_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_service_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
